### ISSUE TITLE
GitHub Action for Flutter build Android APK

### ISSUE THREAD

**Issue by LaansDole** [MedVoice-RMIT-CapStone-2024/MedVoice#41]
```
- uses: cedvdb/action-flutter-build-android@v1
        with:
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"
          # optionals
          build-cmd: flutter build apk --release --flavor dev
          working-directory: ./
```

Need to get some keys

For reference: https://github.com/cedvdb/action-flutter-build-android?tab=readme-ov-file
